### ISSUE TITLE
Models: validate input for create

### ISSUE THREAD

**Issue by alexstuckey** [alexstuckey/durham-volunteering#20]
For models methods such as Cause_model->createCause($array), where an array form is defined in the comments, e.g.

```
$data = array(
    'organisation' => 'organisation,
    'typeID' => 'typeID',
    'contactName' => 'contactName',
    'contactEmail' => 'contactEmail',
    'contactPhone' => 'contactPhone',
    'notes' => 'notes',
);
```

The methods themselves should validate against this schema, to prevent malformed data being arbitrarily entered into the database.

Please create a feature branch and pull request it referring to this issue.

**Comment by alexstuckey** [comment]
We should also discuss how we want to deal with validating relationships.

For instance, what if a cause is created with a typeID that does not exist?
That goes beyond statically checking a inputs form, and requires interacting with the database.

**Comment by JDiggers** [comment]
Pushed to initialValidation branch. The check for existing data before further data can be grafted onto it has been implemented. The validation checks have been added but commented out pending a discussion on how CI interacts with the forms from the model layer.
