### ISSUE TITLE
Convert DB schema to 3rd normal form

### ISSUE THREAD

**Issue by alexstuckey** [alexstuckey/durham-volunteering#3]
Re-design the DB to comply with 3rd normal form.

![er diagram v1](https://user-images.githubusercontent.com/238649/34071496-fc50802a-e26e-11e7-9c43-db326c86858f.png)

Please could it be in SQL form now. That way we can easily populate databases.

**Comment by JDiggers** [comment]
![er diagram 3nf](https://user-images.githubusercontent.com/32936123/34072385-640f0cc2-e27e-11e7-9ffe-7c2f3b5b23a0.PNG)

**Comment by JDiggers** [comment]
NB I couldn't find a boolean type in MYSQL documentation. Substituted with a bit value of 0 or 1.

**Comment by alexstuckey** [comment]
It seems that internally, MySQL just uses `tinyint(1)`.

https://stackoverflow.com/a/3751890/298051

**Comment by JDiggers** [comment]
![er diagram 3nf](https://user-images.githubusercontent.com/32936123/34079069-ac0893be-e31d-11e7-9819-f47a2657568b.PNG)
Revised Edition with TinyInt inserted.
