### ISSUE TITLE
Template the views

### ISSUE THREAD

**Issue by alexstuckey** [alexstuckey/durham-volunteering#32]

**Comment by williamejelias** [comment]
Done an initial templating of the various different html chunks in homepage and have updated the home.php controller to reflect these changes. Its easy to rearrange/ add/ remove sections from the page by changing what chunks are loaded in the home.php controller.

Will have a look at onboarding templating in the same way with the common header and footer html chunks later.

**Comment by williamejelias** [comment]
Done
