### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by alexstuckey** [alexstuckey/durham-volunteering#53]
Create an admin page, based off of the design of the homepage.

## Capabilities
- [x] Maintain list of departments: names, icons, maximum size, (also display registered count)
- [x] Temporarily disable the system
- [x] Broadcast a notification
- [x] Set system admin email(s)
- [x] Set footer icons and URLs
- [x] Email template editing

## Implementation

- [x] Changes receiving controller
- [x] View
- [x] Database table for email templates

## Final
- [x] Restrict access to admins
- [x] General settings

**Comment by alexstuckey** [comment]
Here's the shell to be inserted into Will's templating (#32).

[empty_shell.html.zip](https://github.com/alexstuckey/durham-volunteering/files/1699053/empty_shell.html.zip)

**Comment by alexstuckey** [comment]
Thanks Anina!
Like the addition of the maintenance mode, good idea.

**Comment by JDiggers** [comment]
Wow Anina! Looks really great. Very happy with how these are looking. 

I'll make sure the corresponding functionality is on the backend.
