### ISSUE TITLE
Add personal declaration to shift submission

### ISSUE THREAD

**Issue by alexstuckey** [alexstuckey/durham-volunteering#57]
The existing system requires an acknowledgement of terms before submitting a shift.

Should we implement similar functionality?

![declaration](https://user-images.githubusercontent.com/238649/35418794-57bcb85c-022c-11e8-9d0e-1f8777a89ed5.png)

**Comment by JDiggers** [comment]
Do we need to do this per shift? I think doing it as part of the 'onboarding' process gives us sufficient coverage here.

I don't think this needs to be revisited each time.

**Comment by alexstuckey** [comment]
That should be a follow-up question for the client, as part of our next presentation.
We should give them both options.

**Comment by alexstuckey** [comment]
Let's make it a mock-up for Mile 1, then functional for Mock 2 after the feedback.

**Comment by williamejelias** [comment]
mock-up in the onboarding process or as part of the form for every time a shift application is made?

**Comment by alexstuckey** [comment]
Let's do on boarding for this iteration, then we can show the client.
