### ISSUE TITLE
Create test MySQL database based off ER diagram

### ISSUE THREAD

**Issue by alexstuckey** [alexstuckey/durham-volunteering#6]
Using ER diagram from #3, please create a test MySQL db and upload a SQL file to this issue.

We should discuss whether to use provided Dur Community server, or use local dev instances.

**IMPORTANT: repo is public, no credentials to be committed**

**Comment by JDiggers** [comment]
[Pwvfw82_Durham_Outreach_Volunteering.sql.zip](https://github.com/alexstuckey/durham-volunteering/files/1606713/Pwvfw82_Durham_Outreach_Volunteering.sql.zip)

**Comment by JDiggers** [comment]
The management column mistakenly had the 'ManagersCisID' column as the primary key. As primary keys are unique, this meant that a manager could only manager one person. 

The primary key is now the CisID.
